# Languages
#   Documentation: https://docs.hugoblox.com/reference/language/

# Default language - English
en:
  languageCode: en-us
  languageName: English
  contentDir: content/en
  weight: 1

# Chinese
zh:
  languageCode: zh-Hans
  languageName: 中文
  contentDir: content/zh
  weight: 2
  title: '谢超 | 个人学术主页'
  params:
    description: "谢超的个人学术网站，研究方向：计算精神病学、认知神经科学、自然行为的智能计算分析。"
